In [2]:
import pandas as pd
import numpy as np

In [4]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies=movies.merge(credits,on='title')

In [12]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
#genres
#id
#keyword
#title
#overview
#cast,crew

movies=movies[['movie_id','title','overview','keywords','genres','cast','crew']]

In [16]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
keywords    0
genres      0
cast        0
crew        0
dtype: int64

In [20]:
movies.dropna(inplace=True)

In [22]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [24]:
import ast
ast.literal_eval

In [26]:
movies['genres']=movies['genres'].apply(convert)
movies['keywords']=movies['keywords'].apply(convert)

In [28]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=="Director":
             L.append(i['name'])
             break
    return L

In [32]:
movies['crew']=movies['crew'].apply(fetch_director)

In [33]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [34]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [35]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [36]:
def convert2(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter<3:
            L.append(i['name'])
        counter+=1
    return L

In [37]:
movies['cast']=movies['cast'].apply(convert2)

In [38]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [46]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [48]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [50]:
movies['tag']=movies['overview']+movies['keywords']+ movies['crew']+ movies['cast']

In [52]:
movies.head()

,movie_id,title,overview,keywords,genres,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [54]:
new_df=movies[['movie_id','title','tag']]

In [56]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [58]:
new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

C:\Users\prasa\AppData\Local\Temp\ipykernel_4424\4079141722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

In [60]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [62]:
new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

C:\Users\prasa\AppData\Local\Temp\ipykernel_4424\1740795540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

In [64]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [66]:
import nltk

In [67]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [68]:
new_df['tag'] = new_df['tag'].astype(str)

C:\Users\prasa\AppData\Local\Temp\ipykernel_4424\2302151642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].astype(str)

In [72]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [74]:
new_df['tag'] = new_df['tag'].astype(str).apply(stem)

C:\Users\prasa\AppData\Local\Temp\ipykernel_4424\744104174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag'] = new_df['tag'].astype(str).apply(stem)

In [388]:
new_df

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [106]:
#text ==> vector
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000,stop_words='english')

In [108]:
vector=cv.fit_transform(new_df['tag'])

In [110]:
cv.get_feature_names_out()

array(['000', '10', '1950', '1970', '3d', 'abandon', 'abus', 'accept',
       'accid', 'accident', 'act', 'action', 'actor', 'actual', 'adapt',
       'addict', 'adopt', 'adulteri', 'adventur', 'affair', 'affect',
       'africa', 'african', 'aftercreditssting', 'age', 'agent', 'ago',
       'agre', 'aid', 'airplan', 'alcohol', 'alex', 'alien', 'alive',
       'alli', 'allow', 'alway', 'america', 'american', 'ancient',
       'angel', 'angeles', 'ani', 'anim', 'anoth', 'answer', 'anyth',
       'apart', 'apocalypt', 'appear', 'arm', 'armi', 'arrest', 'arriv',
       'art', 'artist', 'ask', 'aspir', 'assassin', 'assign', 'assist',
       'astronaut', 'attack', 'attempt', 'attract', 'author', 'away',
       'babi', 'bad', 'band', 'bank', 'bar', 'base', 'basebal',
       'basedoncomicbook', 'basedonnovel', 'basedontruestori',
       'basedonyoungadultnovel', 'basketbal', 'battl', 'beach', 'bear',
       'beat', 'beauti', 'becaus', 'becom', 'befor', 'befriend', 'begin',
       'believ', 'belov', 'ben', 'benstil', 'berlin', 'best',
       'bestfriend', 'betray', 'better', 'big', 'biographi', 'birthday',
       'black', 'blackmail', 'blood', 'bodi', 'bomb', 'bond', 'book',
       'born', 'boss', 'box', 'boy', 'boyfriend', 'break', 'bring',
       'british', 'brother', 'brotherbrotherrelationship',
       'brothersisterrelationship', 'brucewilli', 'brutal', 'buddi',
       'build', 'busi', 'businessman', 'california', 'camp', 'cancer',
       'captain', 'captur', 'car', 'care', 'career', 'carri', 'case',
       'cast', 'cat', 'catch', 'caught', 'caus', 'celebr', 'center',
       'centuri', 'century', 'challeng', 'chanc', 'chang', 'charact',
       'charg', 'charli', 'chase', 'chicago', 'child', 'childhood',
       'children', 'china', 'christian', 'christma', 'church', 'cia',
       'citi', 'city', 'civil', 'claim', 'class', 'classic',
       'clinteastwood', 'close', 'club', 'coach', 'collect', 'colleg',
       'come', 'comedi', 'comic', 'comingofag', 'command', 'commit',
       'commun', 'compani', 'compet', 'competit', 'complet', 'complic',
       'comput', 'confront', 'connect', 'conspiraci', 'continu',
       'control', 'convict', 'convinc', 'cop', 'corpor', 'corrupt',
       'countri', 'country', 'coupl', 'courag', 'cours', 'court', 'cover',
       'crash', 'creat', 'creatur', 'crew', 'crime', 'crimin', 'cross',
       'crush', 'curs', 'dad', 'danc', 'dancer', 'danger', 'danni',
       'dark', 'date', 'daughter', 'david', 'day', 'dead', 'deadli',
       'deal', 'dealer', 'death', 'decid', 'deep', 'defeat', 'defend',
       'demand', 'demon', 'desert', 'desir', 'desper', 'despit',
       'destroy', 'detect', 'determin', 'develop', 'die', 'differ',
       'dinosaur', 'direct', 'director', 'disappear', 'discov',
       'discoveri', 'divorc', 'doctor', 'documentari', 'doe', 'doesn',
       'dog', 'don', 'door', 'dr', 'dragon', 'drama', 'drawn', 'dream',
       'drink', 'drive', 'driver', 'drug', 'drugdeal', 'dure',
       'duringcreditssting', 'dyinganddeath', 'dystopia', 'earli',
       'earth', 'east', 'eccentr', 'effort', 'elit', 'embark', 'emot',
       'encount', 'end', 'enemi', 'engag', 'england', 'english', 'enlist',
       'enter', 'entir', 'epic', 'escap', 'especi', 'estrang', 'eve',
       'event', 'eventu', 'everi', 'everyon', 'everyth', 'evil', 'ex',
       'execut', 'exist', 'experi', 'explor', 'explos', 'expos', 'extrem',
       'eye', 'face', 'fail', 'faith', 'fall', 'fame', 'famili', 'family',
       'famou', 'fantasi', 'far', 'farm', 'fast', 'fate', 'father',
       'fathersonrelationship', 'fbi', 'fear', 'featur', 'feel', 'fellow',
       'femal', 'femalenud', 'fiction', 'fight', 'fighter', 'figur',
       'film', 'filmmak', 'final', 'flashback', 'fli', 'florida',
       'follow', 'food', 'forc', 'forest', 'forever', 'form', 'franc',
       'frank', 'free', 'freedom', 'french', 'friend', 'friends',
       'friendship', 'funer', 'futur', 'future', 'game', 'gang',
       'gangster', 'gay', 'gener', 'georg', 'ghost', 'gift', 'girl',
       'girlfriend', 'global', 'god', 'goe', 'gold', 'gone', 'good',
       'gore', 'govern', 'graduat', 'great', 'greatest', 'green', 'group',
       'grow', 'grown', 'guard', 'gun', 'guy', 'ha', 'half', 'hand',
       'happen', 'happi', 'hard', 'harri', 'haunt', 'head', 'heart',
       'heist', 'helicopt', 'hell', 'help', 'henri', 'hero', 'hi', 'hide',
       'high', 'highschool', 'hip', 'hire', 'histori', 'hit', 'hitman',
       'hold', 'holiday', 'hollywood', 'home', 'hometown', 'hop', 'hope',
       'horror', 'hors', 'hospit', 'hostag', 'hot', 'hotel', 'hour',
       'hous', 'house', 'human', 'hunt', 'hunter', 'husband', 'ice',
       'idea', 'ident', 'ii', 'ill', 'immigr', 'includ',
       'independentfilm', 'india', 'indian', 'infidel', 'innoc', 'insid',
       'inspir', 'instead', 'intellig', 'intern', 'interview', 'inventor',
       'investig', 'invit', 'involv', 'irish', 'island', 'isn', 'isol',
       'jack', 'jackson', 'jail', 'jame', 'japan', 'jason', 'jealousi',
       'jean', 'jewish', 'jim', 'jimmi', 'job', 'joe', 'john', 'join',
       'journalist', 'journey', 'jungl', 'just', 'justic', 'kevin', 'key',
       'kid', 'kidnap', 'kids', 'kill', 'killer', 'king', 'kingdom',
       'knight', 'know', 'known', 'la', 'lake', 'land', 'late', 'later',
       'latest', 'law', 'lawyer', 'lead', 'leader', 'learn', 'leav',
       'led', 'lee', 'left', 'legend', 'legendari', 'letter', 'lie',
       'life', 'light', 'like', 'line', 'littl', 'live', 'lives', 'll',
       'lo', 'local', 'london', 'londonengland', 'lone', 'long', 'look',
       'lord', 'losangel', 'lose', 'lost', 'love', 'loveofone', 'lover',
       'luck', 'mad', 'mafia', 'magic', 'major', 'make', 'male', 'man',
       'manag', 'mani', 'mark', 'marri', 'marriag', 'martialart',
       'martin', 'marvelcom', 'mask', 'master', 'match', 'mattdamon',
       'max', 'mean', 'medic', 'meet', 'member', 'memori', 'men',
       'mental', 'mercenari', 'mexican', 'mexico', 'michael', 'middl',
       'mike', 'militari', 'million', 'mind', 'miss', 'mission', 'mob',
       'mobster', 'modern', 'mom', 'money', 'monster', 'month', 'mother',
       'mountain', 'movi', 'movie', 'mr', 'murder', 'music', 'musician',
       'mutant', 'mysteri', 'nation', 'natur', 'nazi', 'near', 'need',
       'neighbor', 'neighborhood', 'neo', 'new', 'newlov', 'news',
       'newyork', 'newyorkc', 'nick', 'nicolascag', 'night', 'nightclub',
       'nightmar', 'noth', 'notori', 'novel', 'nuclear', 'nuditi',
       'number', 'obsess', 'ocean', 'offer', 'offic', 'old', 'older',
       'onc', 'onli', 'open', 'oper', 'opportun', 'order', 'ordinari',
       'organ', 'origin', 'orphan', 'outlaw', 'overcom', 'owner', 'pair',
       'pal', 'parent', 'parents', 'pari', 'park', 'parti', 'partner',
       'pass', 'passion', 'past', 'path', 'paul', 'pay', 'peac', 'peopl',
       'people', 'perfect', 'perform', 'person', 'peter', 'photograph',
       'pilot', 'pirat', 'place', 'plan', 'plane', 'planet', 'play',
       'player', 'plot', 'point', 'polic', 'polit', 'politician',
       'popular', 'possess', 'possibl', 'post', 'power', 'pregnant',
       'prepar', 'present', 'presid', 'prevent', 'priest', 'princ',
       'princess', 'prison', 'privat', 'problem', 'process', 'produc',
       'profession', 'professor', 'program', 'promis', 'prostitut',
       'protect', 'prove', 'psychiatrist', 'psychopath', 'public', 'pull',
       'pursu', 'queen', 'quest', 'question', 'quickli', 'race', 'radio',
       'rais', 'rape', 'ray', 'reach', 'readi', 'real', 'realiti',
       'realiz', 'realli', 'rebel', 'receiv', 'recent', 'record', 'recov',
       'recruit', 'relationship', 'releas', 'remain', 'remak', 'remot',
       'report', 'rescu', 'research', 'resid', 'resist', 'respons',
       'rest', 'restaur', 'result', 'retir', 'return', 'reunit', 'reveal',
       'reveng', 'revenge', 'rich', 'richard', 'ride', 'right', 'ring',
       'rise', 'risk', 'rival', 'rivalri', 'road', 'rob', 'robberi',
       'robert', 'robertdeniro', 'robot', 'rock', 'role', 'romanc',
       'romant', 'romanticcomedi', 'room', 'rule', 'run', 'russian',
       'ruthless', 'ryan', 'safe', 'sam', 'samuell', 'san', 'save',
       'savingtheworld', 'scene', 'scheme', 'school', 'scientist',
       'scott', 'sea', 'search', 'season', 'second', 'secret',
       'secretident', 'secur', 'seek', 'seemingli', 'seen', 'self',
       'sell', 'send', 'sent', 'separ', 'sequel', 'seri', 'serial',
       'serialkil', 'serv', 'servic', 'set', 'seven', 'sever', 'sex',
       'sexual', 'share', 'shark', 'sheriff', 'ship', 'shock', 'shootout',
       'shop', 'shot', 'sign', 'sinc', 'singer', 'singl', 'sister',
       'sistersisterrelationship', 'situat', 'skill', 'slasher', 'slave',
       'slif', 'small', 'smalltown', 'snow', 'social', 'societi',
       'soldier', 'someth', 'son', 'soon', 'soul', 'south', 'space',
       'special', 'spend', 'spi', 'spirit', 'spoof', 'sport', 'stage',
       'stand', 'star', 'start', 'state', 'station', 'stay', 'steal',
       'step', 'steve', 'stolen', 'stop', 'store', 'stori', 'storm',
       'story', 'strand', 'strang', 'stranger', 'street', 'strike',
       'struggl', 'student', 'stumbl', 'success', 'suddenli', 'suffer',
       'suicid', 'summer', 'superhero', 'supernatur', 'superpow',
       'surpris', 'surviv', 'survivor', 'suspect', 'suspens', 'taken',
       'tale', 'talent', 'talk', 'target', 'task', 'teach', 'teacher',
       'team', 'technolog', 'teen', 'teenag', 'televis', 'tell',
       'terrifi', 'terror', 'terrorist', 'test', 'texa', 'themselv',
       'thi', 'thief', 'thing', 'think', 'thought', 'threat', 'threaten',
       'thriller', 'tim', 'time', 'timetravel', 'togeth', 'told', 'tom',
       'tortur', 'tough', 'tour', 'town', 'track', 'tragedi', 'train',
       'transform', 'transport', 'trap', 'travel', 'tri', 'trial', 'trip',
       'troubl', 'true', 'trust', 'truth', 'turn', 'tv', 'twin', 'ultim',
       'uncl', 'uncov', 'undercov', 'underground', 'underworld',
       'unexpect', 'unit', 'univers', 'unlik', 'usa', 'usapresid', 'use',
       'vacat', 'vampir', 'van', 'variou', 'veri', 'veteran', 'victim',
       'video', 'villag', 'villain', 'violenc', 'violent', 'virgin',
       'viru', 'visit', 'wa', 'wait', 'wake', 'walk', 'wall', 'want',
       'war', 'warrior', 'watch', 'water', 'way', 'wealthi', 'weapon',
       'wed', 'week', 'weekend', 'werewolf', 'west', 'white', 'widow',
       'wife', 'wifehusbandrelationship', 'wild', 'william', 'win',
       'winter', 'wish', 'wit', 'witch', 'woman', 'womandirector',
       'women', 'won', 'woodyallen', 'work', 'worker', 'world',
       'worldwarii', 'writer', 'wrong', 'year', 'years', 'york', 'young',
       'younger', 'youth', 'zombi'], dtype=object)

In [82]:
vector.shape

(4806, 2000)

In [84]:
from sklearn.metrics.pairwise import cosine_similarity

In [86]:
similarity=cosine_similarity(vector)

In [88]:
similarity[0]

array([1.        , 0.        , 0.03928371, ..., 0.03121953, 0.        ,
       0.        ])

In [90]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movies_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [92]:
recommend('Avatar')

Aliens vs Predator: Requiem
Falcon Rising
Aliens
Independence Day
Battle: Los Angeles

In [94]:
import pickle

In [96]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [98]:
pickle.load(open('movies.pkl','rb'))

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [100]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [102]:
print(np.__version__)
print(pd.__version__)

1.26.4
2.2.2